package com.cob.fabrica.bean;
// Generated 15/03/2019 17:15:45 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apellido;
     private Long celular;
     private String email;
     private Long whatapp;
     private String direccion;
     private String cuit;

    public String getCuit() {
        return cuit;
    }

    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
   

    public Clientes() {
    }

	
    public Clientes(int idCliente) {
        this.idCliente = idCliente;
    }
    public Clientes(int idCliente, String nombre, String apellido, Long celular, String email, Long whatapp, String direccion, String cuit) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.celular = celular;
       this.email = email;
       this.whatapp = whatapp;
       this.direccion = direccion;
       this.cuit=cuit;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Long getWhatapp() {
        return this.whatapp;
    }
    
    public void setWhatapp(Long whatapp) {
        this.whatapp = whatapp;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


